[build]
  # This tells Netlify where your serverless functions are located.
  functions = "api/"

# This rule makes your single-page application work correctly.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
