[build]
  # This tells Netlify where your serverless functions are.
  functions = "api/"

# --- This is the important block that uses your Pro account feature ---
[functions."search-products"]
  # We are telling Netlify to allow this specific function to run for up to 26 seconds.
  timeout = 26

# This rule tells Netlify how to handle API calls.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# This rule handles all other requests for your single-page app.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
